; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Tue May 28 2019 23:04:08 GMT-0700 (Pacific Daylight Time)

