; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Tue May 28 2019 23:04:08 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P0

